// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaHRYnejVqy9lJN6bxctCU1HXQkmbt4Pw',
    appId: '1:1062502789608:web:236bb3a318a398af8e345d',
    messagingSenderId: '1062502789608',
    projectId: 'st-could',
    authDomain: 'st-could.firebaseapp.com',
    databaseURL: 'https://st-could-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'st-could.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI9Gbn3m5Tol4_KuxifdhZUuuMSyR2mlI',
    appId: '1:1062502789608:android:4e9edce79e32d32a8e345d',
    messagingSenderId: '1062502789608',
    projectId: 'st-could',
    databaseURL: 'https://st-could-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'st-could.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaMth97WLfWTB7CEIxCIfTpnUZ3-UWzm4',
    appId: '1:1062502789608:ios:d084ed6c5c7f35808e345d',
    messagingSenderId: '1062502789608',
    projectId: 'st-could',
    databaseURL: 'https://st-could-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'st-could.firebasestorage.app',
    iosBundleId: 'com.example.xeritech001final',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaMth97WLfWTB7CEIxCIfTpnUZ3-UWzm4',
    appId: '1:1062502789608:ios:d084ed6c5c7f35808e345d',
    messagingSenderId: '1062502789608',
    projectId: 'st-could',
    databaseURL: 'https://st-could-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'st-could.firebasestorage.app',
    iosBundleId: 'com.example.xeritech001final',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaHRYnejVqy9lJN6bxctCU1HXQkmbt4Pw',
    appId: '1:1062502789608:web:38805646c68f3c9f8e345d',
    messagingSenderId: '1062502789608',
    projectId: 'st-could',
    authDomain: 'st-could.firebaseapp.com',
    databaseURL: 'https://st-could-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'st-could.firebasestorage.app',
  );
}
